// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAky_Z35mAoi5bGTNXYa_WZA4crPY-_hk',
    appId: '1:523639837972:web:36935f9eacf76d70b8de01',
    messagingSenderId: '523639837972',
    projectId: 'testproject-ce553',
    authDomain: 'testproject-ce553.firebaseapp.com',
    storageBucket: 'testproject-ce553.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUYTsuo1wfYenL2jppLnZHMKvY8Y-9rc',
    appId: '1:523639837972:android:246eeca3b8c66e8fb8de01',
    messagingSenderId: '523639837972',
    projectId: 'testproject-ce553',
    storageBucket: 'testproject-ce553.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDog2O5bvCWTgQzh6l6RNLRRh2NODjOqrM',
    appId: '1:523639837972:ios:509bcd788dfe935eb8de01',
    messagingSenderId: '523639837972',
    projectId: 'testproject-ce553',
    storageBucket: 'testproject-ce553.appspot.com',
    iosClientId: '523639837972-offu15j2g4c7kut5l9e8qnn3o4honfu0.apps.googleusercontent.com',
    iosBundleId: 'com.dileep.test.videoPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDog2O5bvCWTgQzh6l6RNLRRh2NODjOqrM',
    appId: '1:523639837972:ios:509bcd788dfe935eb8de01',
    messagingSenderId: '523639837972',
    projectId: 'testproject-ce553',
    storageBucket: 'testproject-ce553.appspot.com',
    iosClientId: '523639837972-offu15j2g4c7kut5l9e8qnn3o4honfu0.apps.googleusercontent.com',
    iosBundleId: 'com.dileep.test.videoPlayer',
  );
}
